# Generated by Django 3.0.2 on 2020-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.BigIntegerField()),
                ('Owner', models.CharField(max_length=50)),
                ('OwnerContact', models.BigIntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=25)),
                ('Place', models.CharField(max_length=25)),
                ('Location', models.CharField(max_length=50)),
                ('Uname', models.CharField(max_length=20)),
                ('Pswd', models.CharField(max_length=15)),
            ],
        ),
    ]
