# Generated by Django 3.0.2 on 2020-02-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0002_clinicreg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('clid', models.IntegerField()),
                ('spid', models.IntegerField()),
                ('Photo', models.FileField(upload_to='file')),
            ],
        ),
    ]
