# Generated by Django 3.0.2 on 2020-02-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=25)),
                ('Place', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25)),
                ('Mobile', models.BigIntegerField()),
                ('Uname', models.CharField(max_length=20)),
                ('Pswd', models.CharField(max_length=15)),
            ],
        ),
    ]
