# Generated by Django 3.0.2 on 2020-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='Status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
