# Generated by Django 3.0.2 on 2020-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patientapp', '0002_patientreg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('lid', models.IntegerField()),
                ('spid', models.IntegerField()),
                ('clid', models.IntegerField()),
                ('docid', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Token', models.IntegerField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('Ques', models.CharField(max_length=100)),
                ('Ans', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('Sugg', models.CharField(max_length=100)),
            ],
        ),
    ]
