# Generated by Django 3.0.2 on 2020-02-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patientapp', '0003_appointment_question_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreg',
            name='Status',
        ),
    ]
