# Generated by Django 3.0 on 2020-03-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cno', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('bname', models.IntegerField()),
                ('branch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('bname', models.IntegerField()),
            ],
        ),
    ]
