# Generated by Django 3.0.2 on 2020-02-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField()),
                ('Title', models.CharField(max_length=25)),
                ('File', models.FileField(upload_to='')),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medihis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('Bgroup', models.CharField(max_length=10)),
                ('Height', models.IntegerField()),
                ('Weight', models.ImageField(upload_to='')),
                ('Physician', models.CharField(max_length=25)),
                ('Smoke', models.CharField(max_length=20)),
                ('Drink', models.CharField(max_length=20)),
                ('Disease', models.CharField(max_length=20)),
                ('Reaction', models.CharField(max_length=20)),
                ('Medication', models.CharField(max_length=20)),
                ('Dosage', models.IntegerField()),
                ('Purpose', models.CharField(max_length=30)),
                ('Sugar', models.CharField(max_length=20)),
                ('Allergy', models.CharField(max_length=20)),
                ('Family', models.CharField(max_length=20)),
                ('Immunity', models.CharField(max_length=20)),
                ('Tb', models.CharField(max_length=20)),
                ('Chest', models.CharField(max_length=20)),
                ('Stroke', models.CharField(max_length=20)),
                ('Fever', models.CharField(max_length=20)),
                ('Attack', models.CharField(max_length=20)),
                ('Asthma', models.CharField(max_length=20)),
                ('Pacemaker', models.CharField(max_length=20)),
                ('Thyroid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('Medicine', models.CharField(max_length=50)),
                ('Dosage', models.IntegerField()),
                ('Nod', models.IntegerField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
