# Generated by Django 3.0.2 on 2020-02-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='File',
            field=models.FileField(upload_to='file'),
        ),
    ]
