# Generated by Django 3.0.2 on 2020-02-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0002_auto_20200209_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clid', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('License', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=30)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.CharField(max_length=25)),
                ('Uname', models.CharField(max_length=25)),
                ('Pwd', models.CharField(max_length=25)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
