# Generated by Django 3.0.2 on 2020-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0003_doctorreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='Specialization',
            field=models.CharField(default='', max_length=20),
        ),
    ]
