# Generated by Django 3.0.2 on 2020-02-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0004_doctorreg_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorreg',
            old_name='Name',
            new_name='DrName',
        ),
    ]
