# Generated by Django 3.0.2 on 2020-02-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0005_auto_20200209_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Status',
        ),
    ]
