# Generated by Django 3.0.2 on 2020-02-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0006_remove_prescription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='appid',
            new_name='pid',
        ),
    ]
