# Generated by Django 3.0.2 on 2020-02-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0008_prescription_docid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='pid',
            new_name='appid',
        ),
    ]
