# Generated by Django 3.0.2 on 2020-02-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0009_auto_20200209_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
