# Generated by Django 3.0.2 on 2020-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0011_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('ans', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appid',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Dosage',
            field=models.CharField(default='', max_length=20),
        ),
    ]
