# Generated by Django 3.0.2 on 2020-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0012_auto_20200209_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='medihis',
            name='docid',
            field=models.IntegerField(default=1),
        ),
    ]
