# Generated by Django 3.0.2 on 2020-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0013_medihis_docid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medihis',
            name='Diabetic',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medihis',
            name='MVP',
            field=models.CharField(default='', max_length=20),
        ),
    ]
